{% set name = "wikipedia-api" %}
{% set version = "0.5.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Wikipedia-API-{{ version }}.tar.gz
  sha256: 065c6541e7480b95b14b9607c243fbce6aefe084e6dc58e41ffb313aec472fcd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - requests

test:
  imports:
    - wikipediaapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/martin-majlis/Wikipedia-API
  summary: Python Wrapper for Wikipedia
  description: |
    Wikipedia-API is easy to use Python wrapper for Wikipedias' API. It supports
    extracting texts, sections, links, categories, translations, etc from Wikipedia.
    Documentation provides code snippets for the most common use cases.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
